apiVersion: v1
kind: Service
metadata:
    name: nebnokiapipelinesjavascriptdocker
spec:
    type: LoadBalancer
    ports:
    - port: 8088 
    selector:
        app: nebnokiapipelinesjavascriptdocker
